---
kind: pipeline
type: docker
name: default

steps:
- name: build-branch
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/roarkgit/strago
    username: roarkgit
    password:
      from_secret: github_pat
    tags:
    - ${DRONE_BRANCH}-${DRONE_COMMIT}
  when:
    branch:
      exclude:
        - main
- name: build-main
  image: plugins/docker
  settings:
    registry: ghcr.io
    repo: ghcr.io/roarkgit/strago
    username: roarkgit
    password:
      from_secret: github_pat
    tags:
    - latest
    - main
  when:
    branch:
      - main